spring:
  security:
    user:
      name: test
      password: test
  datasource:
      url: jdbc:h2:file:/Users/mmt10793/Documents/Proj/secured-qrpay/data/sqls
      username: sa
      password: sa
      driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
app:
  config:
    encryption:
      encrypt-key: abcdefgf12345678
    stripe:
      secret-key: sk_test_51N9YoySICLDQPzS3IFljt2LSHKeTbWtVAVmKDnRJQI8hgd8eZs9iYchtAg6KIcvJdwQXPscDrKVkEuODezRwHShf00eQvNqTBO